import { PrismaService } from '../prisma/prisma.service';
import { Decimal } from '@prisma/client/runtime/library';
export declare class CouponsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    findAll(): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        code: string;
        expiresAt: Date | null;
        description: string | null;
        discountType: import(".prisma/client").$Enums.DiscountType;
        discountValue: Decimal;
        maxUses: number | null;
        usedCount: number;
        minOrderAmount: Decimal | null;
        maxDiscountAmount: Decimal | null;
        applicableServiceIds: string[];
        applicablePlanIds: string[];
        startsAt: Date;
    }[]>;
    findOne(id: string): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        code: string;
        expiresAt: Date | null;
        description: string | null;
        discountType: import(".prisma/client").$Enums.DiscountType;
        discountValue: Decimal;
        maxUses: number | null;
        usedCount: number;
        minOrderAmount: Decimal | null;
        maxDiscountAmount: Decimal | null;
        applicableServiceIds: string[];
        applicablePlanIds: string[];
        startsAt: Date;
    } | null>;
    create(dto: {
        code: string;
        description?: string;
        discountType: 'PERCENT' | 'FLAT';
        discountValue: number;
        maxUses?: number;
        minOrderAmount?: number;
        maxDiscountAmount?: number;
        applicableServiceIds?: string[];
        applicablePlanIds?: string[];
        startsAt?: string;
        expiresAt?: string;
    }): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        code: string;
        expiresAt: Date | null;
        description: string | null;
        discountType: import(".prisma/client").$Enums.DiscountType;
        discountValue: Decimal;
        maxUses: number | null;
        usedCount: number;
        minOrderAmount: Decimal | null;
        maxDiscountAmount: Decimal | null;
        applicableServiceIds: string[];
        applicablePlanIds: string[];
        startsAt: Date;
    }>;
    update(id: string, dto: Partial<{
        description: string;
        discountType: 'PERCENT' | 'FLAT';
        discountValue: number;
        maxUses: number;
        minOrderAmount: number;
        maxDiscountAmount: number;
        applicableServiceIds: string[];
        applicablePlanIds: string[];
        expiresAt: string;
        isActive: boolean;
    }>): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        code: string;
        expiresAt: Date | null;
        description: string | null;
        discountType: import(".prisma/client").$Enums.DiscountType;
        discountValue: Decimal;
        maxUses: number | null;
        usedCount: number;
        minOrderAmount: Decimal | null;
        maxDiscountAmount: Decimal | null;
        applicableServiceIds: string[];
        applicablePlanIds: string[];
        startsAt: Date;
    }>;
    delete(id: string): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        code: string;
        expiresAt: Date | null;
        description: string | null;
        discountType: import(".prisma/client").$Enums.DiscountType;
        discountValue: Decimal;
        maxUses: number | null;
        usedCount: number;
        minOrderAmount: Decimal | null;
        maxDiscountAmount: Decimal | null;
        applicableServiceIds: string[];
        applicablePlanIds: string[];
        startsAt: Date;
    }>;
    getUsage(id: string): Promise<{
        id: string;
        customerId: string | null;
        couponId: string;
        orderId: string;
        usedAt: Date;
    }[]>;
    validateCoupon(code: string, planId: string, amount: number, customerId?: string): Promise<{
        valid: boolean;
        couponId: string;
        code: string;
        discountType: import(".prisma/client").$Enums.DiscountType;
        discountValue: number;
        discountAmount: number;
        finalAmount: number;
    }>;
    applyCoupon(couponId: string, orderId: string, customerId?: string): Promise<void>;
    private calculateDiscount;
    bulkGenerate(count: number, prefix: string, dto: {
        discountType: 'PERCENT' | 'FLAT';
        discountValue: number;
        maxUses?: number;
        expiresAt?: string;
    }): Promise<{
        generated: number;
        codes: string[];
    }>;
}
